[workspace]
resolver = "3"
members = ["core", "desktop"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.98"
authors = ["Denis Rizov <d.b.rizov@gmail.com>"]
license = "MIT"
repository = "https://github.com/dbrizov/ferroboy"

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3
